### ISSUE TITLE
Contributing could be easier

### ISSUE THREAD

**Issue by atlidohop** [zillow/react-slider#126]
Currently there are no instructions for developers to run this package locally to be able to test their contributions. To run, changes must be made in `package.json` and files served up locally with an external package, e.g. `live-server`. Not a big deal, but would be nicer if the setup was dead simple.

**Comment by mpowaga** [comment]
`index.html` cannot be easily opened because it tries to load React and other modules directly from `node_modules` folder. These modules are marked as `peerDependencies` and are not installed automatically. Perhaps better solution would be to use cdn to load dependencies in `index.html`. Then it could be opened with:

`open index.html`

or

`python -m SimpleHTTPServer`

or any other command/tool without the need to install dependencies first.

Any other suggestions?

**Comment by Mike-Bell** [comment]
I took a crack at it here https://github.com/mpowaga/react-slider/pull/135

**Comment by stonebk** [comment]
Should be a better dev experience now with #147
