### ISSUE TITLE
Cannot figure out slider size if component is hidden

### ISSUE THREAD

**Issue by DustinHigginbotham** [zillow/react-slider#15]
I have a component that is hidden on initial load, so on your `componentDidMount` you are calling `_handleResize` and that runs `getBoundingClientRect` and it returns all zeros.

Right now, I am calling the `_handleResize` function as a work around when my component is visible. Is there something better I can do?

**Comment by qwtel** [comment]
Hi,

I've run into this problem myself, unfortunately I haven't really come up with a good solution.

I thought about calculating the slider/handle sizes on each `render`, but since it triggers a browser reflow this is prohibitive from a performance standpoint. 

Maybe calculating the sizes only on touch/mouse start would be a compromise.

Your thoughts?

**Comment by DustinHigginbotham** [comment]
That may be a pretty good idea. If it happens fast enough, the user wouldn't notice.

Worst comes to worst, should there be a more public way of saying "hey, I'm visible now" kind of like what I am doing in my work-around.

**Comment by qwtel** [comment]
I've experimentally implemented the idea, but of course it doesn't solve the problem as touch/mouse start don't get called when the element becomes visible.

From a quick google search it seems like there is no clean way to detect visibility changes, so it seems manually calling `_handleResize` is the "most correct" solution anyway (judging form [this answer](http://stackoverflow.com/a/1462510/870615) to a similar stackoverflow question)

**Comment by DustinHigginbotham** [comment]
But the touch/mouse events won't trigger unless the element is visible anyway. In theory, when `mousedown` happens, it could essentially run `_handleResize` assuming that it has visibility. If nothing less, it could check to see if `getBoundingClientRect` has returned all zeros and have it check again.

Do you fear that by the time `mousedown` happens, it would be too late to do all of these things?

**Comment by qwtel** [comment]
The problem is that the sizes are also used for positioning the handles. This means that when you make the slider visible, all the handles are still positioned at 0. Once you start dragging one of them they all "jump" to their correct position.

Performance isn't the problem.

**Comment by veewee** [comment]
We are also facing this problem when the slider is placed in a react-bootstrap TabPane.
Currently, I am solving the issue by triggering a resize event during change of tabs:

```
window.dispatchEvent(new Event('resize'));
```

However, there must be a way to handle this in the slider component.

**Comment by qwtel** [comment]
You could also call `_handleResize` on the component, but it feels a bit "hacky" as well.

It all has to do with the fact that we use absolute pixel values for the handle positions, which can not be calculated before the size of the slider is known.

For the next version of the slider I have planned to position the handles on a percentage basis, which would also allow the slider to pre-render on the server. However, it will require the users to "center" the handles themselves (i.e. when your handle is 50px in width, give it a `margin-left: -25px`), because we also can't know the size of the handle before it is rendered.

**Comment by veewee** [comment]
Great! I am looking forward to the next version :)

**Comment by ccitro** [comment]
I ran into this issue myself, and I submitted a pull request for how I've solved it for my use cases.

For me, checking if upperBound is 0 in componentWillReceiveProps works because my props will always change after the slider becomes visible.  It won't fix all cases, but it doesn't add any overhead and fixes it as long as your props change.

Merge if you think it'd be helpful, and thanks for the slider.

**Comment by whroman** [comment]
The above-mentioned merge was not helping me in the same situation of having a slider be hidden when the app first loads. I managed to fix this in a fork of react-slider where I wrapped the logic within `_handleResize` with a `setTimeout` of 0. I have submitted a PR for this change at #38.

**Comment by AndrewRayCode** [comment]
Why not make the css `left` a % based, so you never have to worry about size? this is biting me because the slider appears on a page with one layout, then a reflow happens and the slider changes size, but it still thinks its the original size

**Comment by qwtel** [comment]
Yes I was thinking about making `left` %-based (see my earlier post), but I haven't come around to implementing it yet.

Also, it's not as simple as I've originally thought. Setting the `left` property on every `touchmove` (as it is now) is not such a good idea, because it's causing _layout_, _paint_ and _composite_ for every new value. Using the pixel-based `transform` would only cause _composite_.
I'm not sure how much `will-change: left` is helping with that, but certainly not much for browsers that don't support it.

So ideally I would have `left` be %-based during normal rendering, but `trasform` and pixel-based while sliding, which is more complicated than just switching to %-based values.

**Comment by 7rulnik** [comment]
I also have a component that is hidden on initial load. I replaced `display: none` by `visibilty: hidden`. It works.
