### ISSUE TITLE
renderThumb: not working using styled component

### ISSUE THREAD

**Issue by vdhyani-binary** [zillow/react-slider#154]
const thumb = (props, state) => <StyledThumb {...props}>{state.valueNow}</StyledThumb>;
renderTumb ={Thumb}

![s1](https://user-images.githubusercontent.com/58029027/71208125-61583700-22ce-11ea-850c-4ae3393200a4.PNG)

above code is showing overlap all the thumb with single showing track, when i used below code instead of above now i can see all track with all the thumb but now i am not getting Thumb rapup.
not working so i used 

![s2](https://user-images.githubusercontent.com/58029027/71208136-6ae19f00-22ce-11ea-987e-93563f34561d.PNG)

renderThumb={(props, state) => <div style={{border:'1px solid black',margin:'20px'}}  {...props}>{state.valueNow}</div>}

**Comment by stonebk** [comment]
Have you looked at the very last example in the documentation? It is using styled-components and `renderThumb`:
https://zillow.github.io/react-slider/

**Comment by vdhyani-binary** [comment]
yes! i have used in same way

**Comment by stonebk** [comment]
Are you referring to the fact that your border and margin is not showing up?

The render function passes `style` as one of the props that you are spreading onto the div, and since it comes after your own `style` attribute, it is overriding it.

You need to merge the style objects if you want to use inline styles like that.

```jsx
renderThumb={(props, state) => <div style={{border:'1px solid black',margin:'20px', ...props.style}} {...props}>{state.valueNow}}
```
