### ISSUE TITLE
Clicking the track does not trigger onAfterChange

### ISSUE THREAD

**Issue by brandonaaron** [zillow/react-slider#180]
## Description

Clicking directly on the track will trigger an `onChange` event but does not trigger `onBeforeChange` nor `onAfterChange`.

## CodeSandbox

This can be seen on the docs but also reproduced in the code sandbox.

[![Edit zillow/react-slider](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bitter-resonance-5qkcl?file=/src/App.js)

**Comment by viters** [comment]
I also would love `onAfterChange` to be triggered after every change. `onChange` triggers too often for some controlled-scenarios in which only the end result matters, where `onAfterChange` would be perfect. Although, now `onAfterChange` is rather useless, because it does not guarantee to capture all user interactions.

**Comment by viters** [comment]
At the same time, `onSliderClick` returns only one value even if slider contains multiple handles. It is less useful than receiving new value, because it is hard to tell which handle did change.

There is a workaround though @brandonaaron , you can bind to `onSliderClick` and use `ReactSlider.getValue`.

@stonebk 
I think one of these scenarios would be worth considering:
- fire `onAfterChange` right after `onChange` at `onSliderMouseDown` - so adding `onAfterChange` to slider track click, which is breaking change
- return whole value instead of only one changed part from `onSliderClick` - it is also breaking change, but I cannot think of any use scenario of `onSliderClick` right now
- return whole value as second parameter of `onSliderClick` - it is not a breaking change, but it's kinda tech debt in my opinion

**Comment by brandonaaron** [comment]
Thanks for the workaround idea. I ended up using that for now.

Passing the whole value as the second parameter of `onSliderClick` makes the most sense to me with the priority of reducing breaking changes. I agree it is tech debt but probably better to take that on, rather than deal with breaking stuff.
