### ISSUE TITLE
Some new values of min, max, value do not correctly propagate

### ISSUE THREAD

**Issue by paulmelnikow** [zillow/react-slider#20]
So, I've encountered an issue where new values of min, max, and value do not correctly propagate.
1. I set min, max, and value to 100, 400, and 182.
2. I update them to 46, 181, and 93.

**Expected behavior:** the new min, max, and value are set to 46, 181, and 93.

**Observed behavior:** the new min, max, and value are set to 100, 181, and 100.

The bug is in `componentWillReceiveProps`. It sets the new value constrained by the old values for min and max, and so on.

Happy to fix this, but thought I'd check if this approach sounded good:
- The new values of min and max should not be trimmed. To accomplish this, set `this.state.min` and `this.state.max` to null before setting either value.
- Set min and max first, then value.

**Comment by paulmelnikow** [comment]
Hmmm, noticed that `_trimAlignValue` is using this.props.min and this.props.max, which in `componentWillRecieveProps` have not been set to their new values. Is that a bug? Or is the intention that the slider ranges can't change?

**Comment by qwtel** [comment]
That is definitely a bug. 

I put it in there because I observed strange behaviour when suppling values that weren't multiples of `step`, so I forced them to be via `_trimAlignValue`. However, I think it should be on the user to provide correct values in the first place (also it says so in the documentation), so I reverted the changes. 

Im not sure if it solves your problem however. Could you check out the current master?

**Comment by paulmelnikow** [comment]
Thanks, this is clearer, but doesn't quite solve it. I think the problem is that the re-trimming of value is happening in `componentWillReceiveProps`, which happens before `this.props.min` and `this.props.max` get their new values.

Should `_trimAlignValue` take optional parameters which override props.min and props.max?

**Comment by paulmelnikow** [comment]
See #21, let me know what you think.
