### ISSUE TITLE
demo vs. code base discrepancy

### ISSUE THREAD

**Issue by canfie1d** [zillow/react-slider#53]
Your demo uses `translate()` to position the handles and seems to work correctly while your codebase uses `left` and doesn't seems to be positioning the handles in the correct place. Which is newer code? `Translate` is more performant in animations so I assume that the demo is an upgraded version. Can that code be made available?

**Comment by qwtel** [comment]
Difficult to explain. So originally I was using `transform` for positioning, but it caused some problems with existing `transform`s on the handles. That's probably the component you are seeing. After that I switched to absolute positioning, but still pixel based.
For the [rewrite of the component](https://github.com/qwtel/react-multi-slider) I'm sticking with absolute positioning, despite the performance implications because
- it allows to position the handles without knowing the size of the slider, which solves all the visibility related problems
- the bars between the handles have to be positioned absolute anyway (I think in theory it would be possible to do it with `scale()`, but that won't do well with bars that have a background image)

**Comment by canfie1d** [comment]
Oh ok, so the demo is using old code?
Why are you using px based values instead of percentage based?

**Comment by qwtel** [comment]
Yes. The reason is that percentage based positioning via transform is relative to the size of the element being transformed (i.e. setting `transform: translateX(50%)` on a handle will offset it by 50% of its width, which is not what we want)

**Comment by gabssnake** [comment]
@qwtel any chances of unifying the two packages or updating this one to accept React 0.14 ?

**Comment by kodama78** [comment]
Hi, I noticed the same discrepancy and have a question. The code base is not positioning the handles correctly and for some reason seems to ignore the `position: relative` from the slider. My question is how do I fix this issue?
