### ISSUE TITLE
Issue with getBoundingClientRect() being called on undefined component

### ISSUE THREAD

**Issue by clayne11** [zillow/react-slider#63]
[This PR](https://github.com/mpowaga/react-slider/pull/38) brought in a setTimeout before calling for getBoundingClientRect(). This can cause an issue in some situations where the component is unmounted before this call is made thus throwing an exception.

**Comment by blanchma** [comment]
Same problem here: Uncaught TypeError: slider.getBoundingClientRect is not a function(anonymous function) @ react-slider.js?b78f:280

**Comment by iest** [comment]
I'm getting the same issue.

**Comment by istrel** [comment]
This issue is caused by updating component and therefore calling extra `this._handleResize`. After that `this.resizeTimeout` value rewritten with new timeout handle although old timeout is not cleared. So after unmounting the old `resizeTimeout` is still going to happen. When it happens it faces empty refs and therefore throws the error

**Comment by mpowaga** [comment]
Closing this issue because #67 has been merged.
